image: golang:1.10

pipelines:
  default:
    - step:
        script:
          - ./scripts/bitbucket-pipelines-default.sh

  custom:
    release:
      - step:
          services:
              - docker
          caches:
              - docker
          script:
              - ./scripts/bitbucket-pipelines-release.sh
